version: "3.9"
services:
  python:
    container_name: "python_kanbanTest"
    tty: true
    build:
      dockerfile: "./container/python/Dockerfile"
    ports:
      - "8000:8000"
    volumes:
      - "./src/python:/app"
      - "./work:/work"
  db1:
    container_name: "postgres_python_kanbanTest"
    image: postgres:14-alpine
    restart: always
    shm_size: 256mb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - "./db1:/var/lib/postgresql/data"
      - "./work:/work"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
volumes:            # 追加
  vendor:     # 追加